name: JunkyardCreek
main: me.sirtyler.JunkyardCreek.JunkyardCreek
version: 1.4
description: >
             Junkyard Creek-Waste Dumping has never been so good!
depend: [Vault]
softdepend: [WorldEdit]
author: SirTyler
commands:
  junkyard:
    description: All Junkyard commands
    usage: /junk help - Display Help
    aliases: [junk, jc]
permissions:
    junkyardcreek.*:
        description: Gives total JunkyardCreek Access
        children:
            junkyardcreek.test: true
            junkyardcreek.fish: true
    junkyardcreek.region.*:
        description: Gives total Region Access
        children:
            junkyardcreek.region.set: true
            junkyardcreek.region.bypass: true
    junkyardcreek.test:
        description: Allows for Test Command.
        default: true
    junkyardcreek.fish:
        description: Allows for Access to JunkyardCreek Fishing.
        default: true
    junkyardcreek.region.set:
        description: Allows for Setting a Fishing Region.
        default: op
    junkyardcreek.region.bypass:
        description: Allows for Region Bypass.
        default: op
